name: C:\ProgramData\Miniconda3  # 你可以自定义环境名称
channels:
  - conda-forge  # 通常使用conda-forge通道以确保兼容性
dependencies:
  - python=3.10  # 指定Python版本（根据你的需求选择合适的版本）
  - gensim=4.3.3
  - mol2vec=0.2.2
  - numpy>=1.26.0
  - pandas=2.2.3
  - rdkit=2024.3.6
  - streamlit=1.43.2
  - pytorch=2.6.0  # 注意：Conda中使用pytorch而不是torch
  - tqdm=4.54.1
  - transformers=4.45.2
  - pip  # 如果需要安装pip包
  - pip:
    - torch==2.6.0  # 如果某些包在Conda中没有，可以通过pip安装
